
services:
  flight-manager:
    build: .
    container_name: flight_manager_app
    ports:
      - "5000:5000"
    volumes:
      - ./database.db:/app/database.db
      - ./static/generated:/app/static/generated
      - ./app.py:/app/app.py  # <--- ESSENCIAL: Espelha o cÃ³digo Python
      - ./templates:/app/templates # <--- ESSENCIAL: Espelha o HTML
    environment:
      - FLASK_ENV=development
    restart: unless-stopped