services:
  flight-manager:
    build: .
    container_name: flight_manager_app
    ports:
      - "5000:5000"
    volumes:
      - ./database.db:/app/database.db
      - ./static:/app/static           # <--- MUDANÃ‡A IMPORTANTE AQUI (Sem o /generated)
      - ./app.py:/app/app.py
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=development
    restart: unless-stopped